Added devenv and userenv artifacts (#239)
* feat(sdk): added devenv and userenv artifacts

* fix(lint)

* feat(cli): improves command naming conventions

* feat(cli): moves prune command to system

* fix(lint)

* fix(cli): properly set subscriber for logging

* fix(sdk): fix devenv in go

* feat(cli): improved logging for registry

* feat(cli): improved logging for worker

* feat(cli): improved logging for agent

* feat(cli): improved logging for worker

* feat(cli): improved logging for agent & worker

diff --git a/.github/workflows/vorpal.yaml b/.github/workflows/vorpal.yaml
--- a/.github/workflows/vorpal.yaml
+++ b/.github/workflows/vorpal.yaml
@@ -157,7 +157,7 @@ jobs:
           tar -xzvf ./vorpal-${ARCH}-${OS}.tar.gz -C ./dist
           rm -rf ./vorpal-${ARCH}-${OS}.tar.gz
 
-      - run: ./dist/vorpal keys generate
+      - run: ./dist/vorpal system keys generate
 
       - uses: actions/github-script@v7
         with:
@@ -180,46 +180,57 @@ jobs:
           sleep 5
 
       - run: |
-          VORPAL_ARTIFACT=$(dist/vorpal artifact --name "vorpal")
+          VORPAL_ARTIFACT=$(dist/vorpal artifact make "vorpal")
           echo "VORPAL_ARTIFACT=$VORPAL_ARTIFACT" >> $GITHUB_ENV
 
       - run: |
-          VORPAL_PROCESS_ARTIFACT=$(dist/vorpal artifact --name "vorpal-process")
+          VORPAL_DEVENV_ARTIFACT=$(dist/vorpal artifact make "vorpal-devenv")
+          echo "VORPAL_DEVENV_ARTIFACT=$VORPAL_DEVENV_ARTIFACT" >> $GITHUB_ENV
+
+      - run: |
+          VORPAL_PROCESS_ARTIFACT=$(dist/vorpal artifact make "vorpal-process")
           echo "VORPAL_PROCESS_ARTIFACT=$VORPAL_PROCESS_ARTIFACT" >> $GITHUB_ENV
 
       - run: |
-          VORPAL_SHELL_ARTIFACT=$(dist/vorpal artifact --name "vorpal-shell")
-          echo "VORPAL_SHELL_ARTIFACT=$VORPAL_SHELL_ARTIFACT" >> $GITHUB_ENV
-
-      - run: |
-          VORPAL_TEST_ARTIFACT=$(dist/vorpal artifact --name "vorpal-test")
+          VORPAL_TEST_ARTIFACT=$(dist/vorpal artifact make "vorpal-test")
           echo "VORPAL_TEST_ARTIFACT=$VORPAL_TEST_ARTIFACT" >> $GITHUB_ENV
 
       - run: |
-          ARTIFACT=$(dist/vorpal artifact --config "Vorpal.go.toml" --name "vorpal")
+          VORPAL_USERENV_ARTIFACT=$(dist/vorpal artifact make "vorpal-userenv")
+          echo "VORPAL_USERENV_ARTIFACT=$VORPAL_USERENV_ARTIFACT" >> $GITHUB_ENV
+
+      - run: |
+          ARTIFACT=$(dist/vorpal artifact make --config "Vorpal.go.toml" "vorpal")
           if [ "$ARTIFACT" != "$VORPAL_ARTIFACT" ]; then
             echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_ARTIFACT"
             exit 1
           fi
 
       - run: |
-          ARTIFACT=$(dist/vorpal artifact --config "Vorpal.go.toml" --name "vorpal-process")
+          ARTIFACT=$(dist/vorpal artifact make --config "Vorpal.go.toml" "vorpal-devenv")
+          if [ "$ARTIFACT" != "$VORPAL_DEVENV_ARTIFACT" ]; then
+            echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_DEVENV_ARTIFACT"
+            exit 1
+          fi
+
+      - run: |
+          ARTIFACT=$(dist/vorpal artifact make --config "Vorpal.go.toml" "vorpal-process")
           if [ "$ARTIFACT" != "$VORPAL_PROCESS_ARTIFACT" ]; then
             echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_PROCESS_ARTIFACT"
             exit 1
           fi
 
       - run: |
-          ARTIFACT=$(dist/vorpal artifact --config "Vorpal.go.toml" --name "vorpal-shell")
-          if [ "$ARTIFACT" != "$VORPAL_SHELL_ARTIFACT" ]; then
-            echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_SHELL_ARTIFACT"
+          ARTIFACT=$(dist/vorpal artifact make --config "Vorpal.go.toml" "vorpal-test")
+          if [ "$ARTIFACT" != "$VORPAL_TEST_ARTIFACT" ]; then
+            echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_TEST_ARTIFACT"
             exit 1
           fi
 
       - run: |
-          ARTIFACT=$(dist/vorpal artifact --config "Vorpal.go.toml" --name "vorpal-test")
-          if [ "$ARTIFACT" != "$VORPAL_TEST_ARTIFACT" ]; then
-            echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_TEST_ARTIFACT"
+          ARTIFACT=$(dist/vorpal artifact make --config "Vorpal.go.toml" "vorpal-userenv")
+          if [ "$ARTIFACT" != "$VORPAL_USERENV_ARTIFACT" ]; then
+            echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_USERENV_ARTIFACT"
             exit 1
           fi
 
