feat(sdk): added devenv and userenv artifacts

diff --git a/.github/workflows/vorpal.yaml b/.github/workflows/vorpal.yaml
--- a/.github/workflows/vorpal.yaml
+++ b/.github/workflows/vorpal.yaml
@@ -184,21 +184,32 @@ jobs:
           echo "VORPAL_ARTIFACT=$VORPAL_ARTIFACT" >> $GITHUB_ENV
 
       - run: |
-          VORPAL_PROCESS_ARTIFACT=$(dist/vorpal artifact --name "vorpal-process")
-          echo "VORPAL_PROCESS_ARTIFACT=$VORPAL_PROCESS_ARTIFACT" >> $GITHUB_ENV
+          VORPAL_DEVENV_ARTIFACT=$(dist/vorpal artifact --name "vorpal-devenv")
+          echo "VORPAL_DEVENV_ARTIFACT=$VORPAL_DEVENV_ARTIFACT" >> $GITHUB_ENV
 
       - run: |
-          VORPAL_SHELL_ARTIFACT=$(dist/vorpal artifact --name "vorpal-shell")
-          echo "VORPAL_SHELL_ARTIFACT=$VORPAL_SHELL_ARTIFACT" >> $GITHUB_ENV
+          VORPAL_PROCESS_ARTIFACT=$(dist/vorpal artifact --name "vorpal-process")
+          echo "VORPAL_PROCESS_ARTIFACT=$VORPAL_PROCESS_ARTIFACT" >> $GITHUB_ENV
 
       - run: |
           VORPAL_TEST_ARTIFACT=$(dist/vorpal artifact --name "vorpal-test")
           echo "VORPAL_TEST_ARTIFACT=$VORPAL_TEST_ARTIFACT" >> $GITHUB_ENV
 
       - run: |
+          VORPAL_USERENV_ARTIFACT=$(dist/vorpal artifact --name "vorpal-userenv")
+          echo "VORPAL_USERENV_ARTIFACT=$VORPAL_USERENV_ARTIFACT" >> $GITHUB_ENV
+
+      - run: |
           ARTIFACT=$(dist/vorpal artifact --config "Vorpal.go.toml" --name "vorpal")
           if [ "$ARTIFACT" != "$VORPAL_ARTIFACT" ]; then
             echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_ARTIFACT"
+            exit 1
+          fi
+
+      - run: |
+          ARTIFACT=$(dist/vorpal artifact --config "Vorpal.go.toml" --name "vorpal-devenv")
+          if [ "$ARTIFACT" != "$VORPAL_DEVENV_ARTIFACT" ]; then
+            echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_DEVENV_ARTIFACT"
             exit 1
           fi
 
@@ -210,16 +221,16 @@ jobs:
           fi
 
       - run: |
-          ARTIFACT=$(dist/vorpal artifact --config "Vorpal.go.toml" --name "vorpal-shell")
-          if [ "$ARTIFACT" != "$VORPAL_SHELL_ARTIFACT" ]; then
-            echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_SHELL_ARTIFACT"
+          ARTIFACT=$(dist/vorpal artifact --config "Vorpal.go.toml" --name "vorpal-test")
+          if [ "$ARTIFACT" != "$VORPAL_TEST_ARTIFACT" ]; then
+            echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_TEST_ARTIFACT"
             exit 1
           fi
 
       - run: |
-          ARTIFACT=$(dist/vorpal artifact --config "Vorpal.go.toml" --name "vorpal-test")
-          if [ "$ARTIFACT" != "$VORPAL_TEST_ARTIFACT" ]; then
-            echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_TEST_ARTIFACT"
+          ARTIFACT=$(dist/vorpal artifact --config "Vorpal.go.toml" --name "vorpal-userenv")
+          if [ "$ARTIFACT" != "$VORPAL_USERENV_ARTIFACT" ]; then
+            echo "Go SDK invalid match to Rust: $ARTIFACT != $VORPAL_USERENV_ARTIFACT"
             exit 1
           fi
 
